version: "3"
services:
  db:
    image: postgres
    container_name: scout-db
    environment:
      POSTGRES_PASSWORD: 99tablet
      POSTGRES_USER: root
      POSTGRES_DB: ScoutApp
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - scout-network
  app:
    build: 
      context: .
    environment:
      DB_HOST : db
      DB_PORT : 5432
      DB_USER : root
      DB_PASSWORD : 99tablet
      DB_NAME : ScoutApp
    image: scout-app-db
    ports:
      - 13000:3000
    depends_on:
      - db
    networks:
      - scout-network


volumes:
  db_data:

networks:
  scout-network: